services:
  smtp:
    container_name: starter-kit-smtp
    image: axllent/mailpit:latest
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8025:8025"
    environment:
      - MP_STORAGE=file
      - MP_DATABASE=/data/mailpit.db
    volumes:
      - smtp_data:/data
    restart: unless-stopped

  s3:
    container_name: "starter-kit-s3"
    image: minio/minio:latest
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - s3_data:/data
      - ./init-minio.sh:/usr/local/bin/init-minio.sh
    entrypoint: ["/bin/sh", "/usr/local/bin/init-minio.sh"]
    restart: unless-stopped

volumes:
  s3_data:
  smtp_data:
