services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - DEBUG=${DEBUG:-0}
      - SERVICES=s3
      - PERSISTENCE=ALL
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./temp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh"
      - "./s3-cors-config.json:/etc/localstack/init/ready.d/s3-cors-config.json"

  mailpit:
    container_name: "mailpit"
    image: axllent/mailpit:latest
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    environment:
      - MP_STORAGE=file
      - MP_DATABASE=/data/mailpit.db
    volumes:
      - "./temp/mailpit:/data"
    restart: unless-stopped

  # Uncomment tthe following lines to enable Valkey services
  # valkey can be used as a kv for storing the users sessions, other data and caching
  # valkey:
  #   container_name: "valkey"
  #   image: valkey/valkey:8.1.1-alpine
  #   ports:
  #     - "6379:6379"
  #   environment:
  #     - VALKEY_DATA_DIR=/data
  #   volumes:
  #     - "./temp/valkey:/data"
  #   restart: unless-stopped
